/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DJAAUAzJKMO
 */
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuRadioItem, DropdownMenuRadioGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function BatteryInventory() {
  return (
    <div className="flex flex-col w-full">
      <header className="flex items-center justify-between p-4">
        <h1 className="text-2xl font-semibold">EV Battery Dashboard</h1>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline">
              <FilterIcon className="w-4 h-4 mr-2" />
              Filter
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent className="w-56">
            <DropdownMenuLabel>Sort by</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuRadioGroup defaultValue="soh">
              <DropdownMenuRadioItem value="soh">State of Health (SoH)</DropdownMenuRadioItem>
              <DropdownMenuRadioItem value="type">Battery Type</DropdownMenuRadioItem>
            </DropdownMenuRadioGroup>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <div className="border shadow-sm rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>UUID</TableHead>
              <TableHead>User ID</TableHead>
              <TableHead>Type of EV Battery Cell</TableHead>
              <TableHead>Manufacturer</TableHead>
              <TableHead>End of Life Time (EoL Time)</TableHead>
              <TableHead>State of Health (%)</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>123456789</TableCell>
              <TableCell>001</TableCell>
              <TableCell>Lithium-ion</TableCell>
              <TableCell>Tesla</TableCell>
              <TableCell>2025</TableCell>
              <TableCell className="bg-green-200">80%</TableCell>
              <TableCell>First Life</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>987654321</TableCell>
              <TableCell>002</TableCell>
              <TableCell>Nickel-Metal Hydride</TableCell>
              <TableCell>Toyota</TableCell>
              <TableCell>2023</TableCell>
              <TableCell className="bg-blue-200">60%</TableCell>
              <TableCell>Purchased</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>456789123</TableCell>
              <TableCell>003</TableCell>
              <TableCell>Lithium-ion</TableCell>
              <TableCell>Nissan</TableCell>
              <TableCell>2024</TableCell>
              <TableCell className="bg-red-200">40%</TableCell>
              <TableCell>Second Life</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>789123456</TableCell>
              <TableCell>004</TableCell>
              <TableCell>Nickel-Metal Hydride</TableCell>
              <TableCell>General Motors</TableCell>
              <TableCell>2026</TableCell>
              <TableCell className="bg-green-200">85%</TableCell>
              <TableCell>Recycled</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>321654987</TableCell>
              <TableCell>005</TableCell>
              <TableCell>Lithium-ion</TableCell>
              <TableCell>BMW</TableCell>
              <TableCell>2027</TableCell>
              <TableCell className="bg-blue-200">65%</TableCell>
              <TableCell>Requested</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}
